### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by supertxtnet** [benoitkugler/oksvg#2]
This project is interesting architecturally because of the driver interface allowing other rendering backends, such as canvas, or even gioui so that it can be used directly in GUI apps.

Unfortunately because there's no license, the API is invisible to pkg.go.dev, and also discourages others from contributing. Any chance that a license can be added?

**Comment by benoitkugler** [comment]
Sure thing, I've added the BSD-3 license. 

Thank you for your interest in this package.

**Comment by supertxtnet** [comment]
Thanks!
