### ISSUE TITLE
Param mismatch error on svg's generated from graphviz

### ISSUE THREAD

**Issue by supertxtnet** [benoitkugler/oksvg#3]
When generating svg using graphviz, most other programs (fireofx, inkscape, gnome preview) have no problem rendering it. But, oksvg seems to complain about "param mismatch" when parsing it. See the attached example, but other kinds of graphviz diagrams exhibit the same behaviour. I suspect that there's something going wrong in the path parsing.

![baz](https://github.com/benoitkugler/oksvg/assets/129553648/39ddde7f-21c5-43ff-9213-54d2957efaae)

**Comment by benoitkugler** [comment]
The issue you found was actually about color parsing (the transparent keyword was not supported). Commit 1380579 fix this issue.
You won't be able to properly display you icon though, since text is not supported.

**Comment by supertxtnet** [comment]
Thanks! This is working minus the text portions.
